# Render deployment configuration for Backend
# 
# In Render Dashboard, set these values:
# Build Command: npm run build
# Start Command: npm start
# Root Directory: server
#
# Environment Variables to set in Render:
# DATABASE_URL=your_supabase_connection_string
# JWT_SECRET=your_jwt_secret
# ADMIN_EMAIL=admin@redconnect.org
# ADMIN_PASSWORD=admin123
# NODE_ENV=production
# FRONTEND_URL=https://your-vercel-app.vercel.app
